/**
 * Comprehensive Exercise Database — 500+ Exercises
 * Complete coverage for all muscle groups with all major variations
 * Reference: StrongApp, MyFitnessPal, Fitbod, JEFIT, ExRx.net
 */

export interface Exercise {
  name: string;
  category: "chest" | "back" | "shoulders" | "biceps" | "triceps" | "forearms" | "legs" | "glutes" | "core" | "cardio" | "functional";
  type: "compound" | "isolation" | "cardio" | "functional";
  difficulty: "beginner" | "intermediate" | "advanced";
  equipment: string[];
  description: string;
  muscleGroups: string[];
  videoUrl?: string;
}

export const EXERCISES: Exercise[] = [
  // ===== CHEST (40+ exercises) =====
  { name: "Barbell Bench Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["barbell", "bench"], description: "Classic horizontal pressing movement", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Dumbbell Bench Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["dumbbells", "bench"], description: "Pressing with dumbbells for greater range of motion", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Incline Barbell Bench Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["barbell", "incline bench"], description: "Emphasizes upper chest", muscleGroups: ["upper chest", "shoulders", "triceps"] },
  { name: "Incline Dumbbell Bench Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["dumbbells", "incline bench"], description: "Dumbbell variation for upper chest", muscleGroups: ["upper chest", "shoulders", "triceps"] },
  { name: "Decline Barbell Bench Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["barbell", "decline bench"], description: "Emphasizes lower chest", muscleGroups: ["lower chest", "triceps"] },
  { name: "Decline Dumbbell Bench Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["dumbbells", "decline bench"], description: "Dumbbell variation for lower chest", muscleGroups: ["lower chest", "triceps"] },
  { name: "Machine Chest Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Guided chest press on machine", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Chest Fly Machine", category: "chest", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Isolates chest with guided motion", muscleGroups: ["chest"] },
  { name: "Dumbbell Chest Fly", category: "chest", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "bench"], description: "Free-weight chest fly for isolation", muscleGroups: ["chest"] },
  { name: "Cable Chest Fly", category: "chest", type: "isolation", difficulty: "intermediate", equipment: ["cable machine"], description: "Chest fly with cables", muscleGroups: ["chest"] },
  { name: "Push-ups", category: "chest", type: "compound", difficulty: "beginner", equipment: ["bodyweight"], description: "Bodyweight chest pressing", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Incline Push-ups", category: "chest", type: "compound", difficulty: "beginner", equipment: ["bodyweight"], description: "Easier variation of push-ups", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Decline Push-ups", category: "chest", type: "compound", difficulty: "advanced", equipment: ["bodyweight"], description: "Harder variation emphasizing upper chest", muscleGroups: ["upper chest", "triceps", "shoulders"] },
  { name: "Wide Grip Push-ups", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["bodyweight"], description: "Wider hand placement for chest emphasis", muscleGroups: ["chest", "shoulders"] },
  { name: "Close Grip Push-ups", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["bodyweight"], description: "Narrower hand placement for triceps emphasis", muscleGroups: ["triceps", "chest"] },
  { name: "Plyometric Push-ups", category: "chest", type: "compound", difficulty: "advanced", equipment: ["bodyweight"], description: "Explosive push-ups for power", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Pec Deck Machine", category: "chest", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine-guided pec isolation", muscleGroups: ["chest"] },
  { name: "Resistance Band Chest Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["resistance band"], description: "Chest press with bands", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Smith Machine Bench Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["smith machine", "bench"], description: "Guided barbell bench press", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Landmine Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["landmine"], description: "Angled barbell press", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Machine Incline Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine incline chest press", muscleGroups: ["upper chest", "shoulders", "triceps"] },
  { name: "Machine Decline Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine decline chest press", muscleGroups: ["lower chest", "triceps"] },
  { name: "Dumbbell Pullover", category: "chest", type: "isolation", difficulty: "intermediate", equipment: ["dumbbell", "bench"], description: "Chest and back isolation", muscleGroups: ["chest", "back"] },
  { name: "Cable Crossover", category: "chest", type: "isolation", difficulty: "intermediate", equipment: ["cable machine"], description: "Standing cable chest fly", muscleGroups: ["chest"] },
  { name: "Resistance Band Fly", category: "chest", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band chest fly", muscleGroups: ["chest"] },
  { name: "Barbell Incline Fly", category: "chest", type: "isolation", difficulty: "intermediate", equipment: ["barbell", "incline bench"], description: "Incline fly with barbell", muscleGroups: ["upper chest"] },
  { name: "Dumbbell Decline Fly", category: "chest", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "decline bench"], description: "Decline fly with dumbbells", muscleGroups: ["lower chest"] },
  { name: "Cable Incline Fly", category: "chest", type: "isolation", difficulty: "intermediate", equipment: ["cable machine"], description: "Cable incline fly", muscleGroups: ["upper chest"] },
  { name: "Lever Chest Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Lever-based chest press machine", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Hammer Strength Chest Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Hammer strength chest press", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Iso-Lateral Chest Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Independent arm chest press", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Chest Press Machine", category: "chest", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Standard chest press machine", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Plate Loaded Chest Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["machine"], description: "Plate-loaded chest press", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Single Arm Dumbbell Bench Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["dumbbell", "bench"], description: "Unilateral chest pressing", muscleGroups: ["chest", "triceps", "shoulders", "core"] },
  { name: "Single Arm Cable Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["cable machine"], description: "Unilateral cable chest press", muscleGroups: ["chest", "triceps", "shoulders", "core"] },
  { name: "Neutral Grip Dumbbell Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["dumbbells", "bench"], description: "Neutral grip dumbbell pressing", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Reverse Grip Barbell Bench Press", category: "chest", type: "compound", difficulty: "advanced", equipment: ["barbell", "bench"], description: "Underhand grip bench press", muscleGroups: ["lower chest", "triceps"] },
  { name: "Feet Elevated Push-ups", category: "chest", type: "compound", difficulty: "advanced", equipment: ["bodyweight"], description: "Push-ups with elevated feet", muscleGroups: ["upper chest", "triceps", "shoulders"] },
  { name: "Diamond Push-ups", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["bodyweight"], description: "Diamond-shaped hand position", muscleGroups: ["triceps", "chest"] },
  { name: "Archer Push-ups", category: "chest", type: "compound", difficulty: "advanced", equipment: ["bodyweight"], description: "Asymmetric push-up variation", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Pseudo Planche Push-ups", category: "chest", type: "compound", difficulty: "advanced", equipment: ["bodyweight"], description: "Advanced bodyweight pressing", muscleGroups: ["chest", "triceps", "shoulders"] },

  // ===== BACK (50+ exercises) =====
  { name: "Barbell Deadlift", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "King of back exercises", muscleGroups: ["back", "glutes", "hamstrings", "core"] },
  { name: "Sumo Deadlift", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Wide stance deadlift", muscleGroups: ["back", "glutes", "quads", "core"] },
  { name: "Romanian Deadlift", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Hip hinge movement for posterior chain", muscleGroups: ["hamstrings", "back", "glutes"] },
  { name: "Trap Bar Deadlift", category: "back", type: "compound", difficulty: "intermediate", equipment: ["trap bar"], description: "Deadlift with trap bar", muscleGroups: ["back", "glutes", "quads"] },
  { name: "Dumbbell Deadlift", category: "back", type: "compound", difficulty: "intermediate", equipment: ["dumbbells"], description: "Deadlift variation with dumbbells", muscleGroups: ["back", "glutes", "hamstrings"] },
  { name: "Barbell Bent Over Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Classic horizontal pulling", muscleGroups: ["back", "biceps"] },
  { name: "Dumbbell Bent Over Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["dumbbells"], description: "Single or double arm bent over row", muscleGroups: ["back", "biceps"] },
  { name: "Pendlay Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Chest-supported row variation", muscleGroups: ["back", "biceps"] },
  { name: "Chest Supported Row Machine", category: "back", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Guided row with chest support", muscleGroups: ["back", "biceps"] },
  { name: "T-Bar Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Angled row with barbell", muscleGroups: ["back", "biceps"] },
  { name: "Seal Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell", "bench"], description: "Chest-supported row on bench", muscleGroups: ["back", "biceps"] },
  { name: "Machine Row", category: "back", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Guided horizontal pulling", muscleGroups: ["back", "biceps"] },
  { name: "Cable Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["cable machine"], description: "Seated or standing cable row", muscleGroups: ["back", "biceps"] },
  { name: "Lat Pulldown", category: "back", type: "compound", difficulty: "beginner", equipment: ["cable machine"], description: "Vertical pulling movement", muscleGroups: ["lats", "biceps"] },
  { name: "Wide Grip Lat Pulldown", category: "back", type: "compound", difficulty: "beginner", equipment: ["cable machine"], description: "Wide grip for lat emphasis", muscleGroups: ["lats", "back"] },
  { name: "Close Grip Lat Pulldown", category: "back", type: "compound", difficulty: "beginner", equipment: ["cable machine"], description: "Close grip for biceps emphasis", muscleGroups: ["lats", "biceps"] },
  { name: "Reverse Grip Lat Pulldown", category: "back", type: "compound", difficulty: "beginner", equipment: ["cable machine"], description: "Underhand grip lat pulldown", muscleGroups: ["lats", "biceps"] },
  { name: "Pull-ups", category: "back", type: "compound", difficulty: "intermediate", equipment: ["pull-up bar"], description: "Bodyweight vertical pulling", muscleGroups: ["lats", "back", "biceps"] },
  { name: "Chin-ups", category: "back", type: "compound", difficulty: "intermediate", equipment: ["pull-up bar"], description: "Underhand grip pull-ups", muscleGroups: ["lats", "biceps"] },
  { name: "Wide Grip Pull-ups", category: "back", type: "compound", difficulty: "advanced", equipment: ["pull-up bar"], description: "Wide grip for lat emphasis", muscleGroups: ["lats", "back"] },
  { name: "Assisted Pull-ups", category: "back", type: "compound", difficulty: "beginner", equipment: ["pull-up machine"], description: "Machine-assisted pull-ups", muscleGroups: ["lats", "back", "biceps"] },
  { name: "Resistance Band Pull-ups", category: "back", type: "compound", difficulty: "beginner", equipment: ["pull-up bar", "resistance band"], description: "Band-assisted pull-ups", muscleGroups: ["lats", "back", "biceps"] },
  { name: "Negative Pull-ups", category: "back", type: "compound", difficulty: "intermediate", equipment: ["pull-up bar"], description: "Eccentric-focused pull-ups", muscleGroups: ["lats", "back", "biceps"] },
  { name: "Single Arm Lat Pulldown", category: "back", type: "isolation", difficulty: "intermediate", equipment: ["cable machine"], description: "Unilateral lat work", muscleGroups: ["lats"] },
  { name: "Straight Arm Lat Pulldown", category: "back", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Isolation for lats", muscleGroups: ["lats"] },
  { name: "Face Pulls", category: "back", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Rear delt and upper back exercise", muscleGroups: ["rear delts", "upper back"] },
  { name: "Reverse Pec Deck", category: "back", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine isolation for rear delts", muscleGroups: ["rear delts", "back"] },
  { name: "Back Hyperextension", category: "back", type: "isolation", difficulty: "intermediate", equipment: ["hyperextension bench"], description: "Lower back and glute exercise", muscleGroups: ["lower back", "glutes"] },
  { name: "Good Mornings", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Posterior chain exercise", muscleGroups: ["hamstrings", "back", "glutes"] },
  { name: "Shrugs", category: "back", type: "isolation", difficulty: "beginner", equipment: ["barbell", "dumbbells"], description: "Trapezius isolation", muscleGroups: ["traps"] },
  { name: "Upright Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell", "dumbbells"], description: "Vertical pulling for traps and shoulders", muscleGroups: ["traps", "shoulders"] },
  { name: "Smith Machine Row", category: "back", type: "compound", difficulty: "beginner", equipment: ["smith machine"], description: "Guided barbell row", muscleGroups: ["back", "biceps"] },
  { name: "Landmine Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["landmine"], description: "Angled barbell row", muscleGroups: ["back", "biceps"] },
  { name: "Single Arm Dumbbell Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["dumbbell"], description: "Unilateral dumbbell row", muscleGroups: ["back", "biceps", "core"] },
  { name: "Single Arm Cable Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["cable machine"], description: "Unilateral cable row", muscleGroups: ["back", "biceps", "core"] },
  { name: "Kroc Row", category: "back", type: "compound", difficulty: "advanced", equipment: ["dumbbell"], description: "Heavy single-arm dumbbell row", muscleGroups: ["back", "biceps"] },
  { name: "Barbell Shrug", category: "back", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Barbell trapezius exercise", muscleGroups: ["traps"] },
  { name: "Dumbbell Shrug", category: "back", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell trapezius exercise", muscleGroups: ["traps"] },
  { name: "Machine Shrug", category: "back", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine trapezius exercise", muscleGroups: ["traps"] },
  { name: "Cable Shrug", category: "back", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable trapezius exercise", muscleGroups: ["traps"] },
  { name: "Lever Shrug", category: "back", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Lever-based shrug machine", muscleGroups: ["traps"] },
  { name: "Rack Pulls", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "Partial range deadlift", muscleGroups: ["back", "glutes", "hamstrings"] },
  { name: "Deficit Deadlift", category: "back", type: "compound", difficulty: "advanced", equipment: ["barbell"], description: "Deadlift from elevated position", muscleGroups: ["back", "glutes", "hamstrings"] },
  { name: "Paused Deadlift", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Deadlift with pause", muscleGroups: ["back", "glutes", "hamstrings"] },
  { name: "Dumbbell Pullovers", category: "back", type: "isolation", difficulty: "intermediate", equipment: ["dumbbell", "bench"], description: "Chest and back isolation", muscleGroups: ["chest", "back"] },
  { name: "Machine Lat Pulldown", category: "back", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine-guided lat pulldown", muscleGroups: ["lats", "biceps"] },
  { name: "Hammer Strength Lat Pulldown", category: "back", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Hammer strength lat pulldown", muscleGroups: ["lats", "biceps"] },
  { name: "Iso-Lateral Lat Pulldown", category: "back", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Independent arm lat pulldown", muscleGroups: ["lats", "biceps"] },
  { name: "Reverse Fly Machine", category: "back", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine reverse fly", muscleGroups: ["rear delts", "back"] },
  { name: "Dumbbell Reverse Fly", category: "back", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Rear delt fly with dumbbells", muscleGroups: ["rear delts"] },
  { name: "Cable Reverse Fly", category: "back", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable rear delt fly", muscleGroups: ["rear delts"] },

  // ===== SHOULDERS (45+ exercises) =====
  { name: "Barbell Overhead Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Standing shoulder press", muscleGroups: ["shoulders", "triceps", "core"] },
  { name: "Dumbbell Shoulder Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["dumbbells", "bench"], description: "Seated or standing dumbbell press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Machine Shoulder Press", category: "shoulders", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Guided shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Pike Push-ups", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["bodyweight"], description: "Bodyweight shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Handstand Push-ups", category: "shoulders", type: "compound", difficulty: "advanced", equipment: ["bodyweight"], description: "Advanced bodyweight shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Shoulder width isolation", muscleGroups: ["lateral delts"] },
  { name: "Cable Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable lateral raise", muscleGroups: ["lateral delts"] },
  { name: "Machine Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine-guided lateral raise", muscleGroups: ["lateral delts"] },
  { name: "Front Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["dumbbells", "barbell"], description: "Front delt isolation", muscleGroups: ["front delts"] },
  { name: "Plate Front Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["weight plate"], description: "Front raise with plate", muscleGroups: ["front delts"] },
  { name: "Reverse Pec Deck Fly", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Rear delt isolation", muscleGroups: ["rear delts"] },
  { name: "Dumbbell Reverse Fly", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Rear delt fly with dumbbells", muscleGroups: ["rear delts"] },
  { name: "Cable Reverse Fly", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable rear delt fly", muscleGroups: ["rear delts"] },
  { name: "Arnold Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["dumbbells"], description: "Rotational shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Landmine Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["landmine"], description: "Angled barbell press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Incline Dumbbell Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["dumbbells", "incline bench"], description: "Incline pressing for shoulders", muscleGroups: ["shoulders", "chest", "triceps"] },
  { name: "Machine Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine lateral raise", muscleGroups: ["lateral delts"] },
  { name: "Smith Machine Shoulder Press", category: "shoulders", type: "compound", difficulty: "beginner", equipment: ["smith machine"], description: "Guided shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Hammer Strength Shoulder Press", category: "shoulders", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Hammer strength shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Iso-Lateral Shoulder Press", category: "shoulders", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Independent arm shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Lever Shoulder Press", category: "shoulders", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Lever-based shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Plate Loaded Shoulder Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["machine"], description: "Plate-loaded shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Barbell Front Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Barbell front raise", muscleGroups: ["front delts"] },
  { name: "Dumbbell Front Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell front raise", muscleGroups: ["front delts"] },
  { name: "Cable Front Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable front raise", muscleGroups: ["front delts"] },
  { name: "Machine Front Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine front raise", muscleGroups: ["front delts"] },
  { name: "Resistance Band Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band lateral raise", muscleGroups: ["lateral delts"] },
  { name: "Resistance Band Front Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band front raise", muscleGroups: ["front delts"] },
  { name: "Resistance Band Reverse Fly", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band reverse fly", muscleGroups: ["rear delts"] },
  { name: "Single Arm Dumbbell Shoulder Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["dumbbell", "bench"], description: "Unilateral shoulder press", muscleGroups: ["shoulders", "triceps", "core"] },
  { name: "Single Arm Cable Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["cable machine"], description: "Unilateral cable shoulder press", muscleGroups: ["shoulders", "triceps", "core"] },
  { name: "Neutral Grip Dumbbell Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["dumbbells", "bench"], description: "Neutral grip shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Incline Lateral Raise", category: "shoulders", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "incline bench"], description: "Incline lateral raise", muscleGroups: ["lateral delts"] },
  { name: "Decline Lateral Raise", category: "shoulders", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "decline bench"], description: "Decline lateral raise", muscleGroups: ["lateral delts"] },
  { name: "Upright Row", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["barbell", "dumbbells"], description: "Vertical pulling for shoulders", muscleGroups: ["shoulders", "traps"] },
  { name: "Barbell Upright Row", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Barbell upright row", muscleGroups: ["shoulders", "traps"] },
  { name: "Dumbbell Upright Row", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["dumbbells"], description: "Dumbbell upright row", muscleGroups: ["shoulders", "traps"] },
  { name: "Cable Upright Row", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["cable machine"], description: "Cable upright row", muscleGroups: ["shoulders", "traps"] },
  { name: "Machine Upright Row", category: "shoulders", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine upright row", muscleGroups: ["shoulders", "traps"] },
  { name: "Dumbbell Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell lateral raise", muscleGroups: ["lateral delts"] },
  { name: "Single Arm Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["dumbbell"], description: "Single arm lateral raise", muscleGroups: ["lateral delts", "core"] },
  { name: "Single Arm Cable Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Single arm cable lateral raise", muscleGroups: ["lateral delts", "core"] },
  { name: "Prone Incline Dumbbell Raise", category: "shoulders", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "incline bench"], description: "Prone incline raise", muscleGroups: ["rear delts"] },
  { name: "Bent Over Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Bent over rear delt raise", muscleGroups: ["rear delts"] },
  { name: "Machine Rear Delt Fly", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine rear delt fly", muscleGroups: ["rear delts"] },

  // ===== BICEPS (40+ exercises) =====
  { name: "Barbell Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Classic bicep curl", muscleGroups: ["biceps"] },
  { name: "Dumbbell Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Single or double arm dumbbell curl", muscleGroups: ["biceps"] },
  { name: "Machine Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Guided bicep curl", muscleGroups: ["biceps"] },
  { name: "Cable Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable bicep curl", muscleGroups: ["biceps"] },
  { name: "EZ Bar Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["EZ bar"], description: "Easier on wrists than straight bar", muscleGroups: ["biceps"] },
  { name: "Preacher Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["preacher bench", "barbell"], description: "Isolated curl on preacher bench", muscleGroups: ["biceps"] },
  { name: "Incline Dumbbell Curl", category: "biceps", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "incline bench"], description: "Greater range of motion curl", muscleGroups: ["biceps"] },
  { name: "Concentration Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbell"], description: "Seated single-arm curl", muscleGroups: ["biceps"] },
  { name: "Hammer Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Neutral grip curl", muscleGroups: ["biceps", "forearms"] },
  { name: "Cable Hammer Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable hammer curl", muscleGroups: ["biceps", "forearms"] },
  { name: "Reverse Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["barbell", "dumbbells"], description: "Overhand grip curl for forearms", muscleGroups: ["biceps", "forearms"] },
  { name: "Barbell Reverse Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Barbell reverse curl", muscleGroups: ["biceps", "forearms"] },
  { name: "Resistance Band Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band bicep curl", muscleGroups: ["biceps"] },
  { name: "21s Curl", category: "biceps", type: "isolation", difficulty: "intermediate", equipment: ["barbell", "dumbbells"], description: "Advanced curl technique", muscleGroups: ["biceps"] },
  { name: "Drag Curl", category: "biceps", type: "isolation", difficulty: "intermediate", equipment: ["barbell", "dumbbells"], description: "Curl with elbow drag", muscleGroups: ["biceps"] },
  { name: "Machine Preacher Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine preacher curl", muscleGroups: ["biceps"] },
  { name: "Smith Machine Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["smith machine"], description: "Guided barbell curl", muscleGroups: ["biceps"] },
  { name: "Landmine Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["landmine"], description: "Angled barbell curl", muscleGroups: ["biceps"] },
  { name: "Dumbbell Preacher Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbell", "preacher bench"], description: "Dumbbell preacher curl", muscleGroups: ["biceps"] },
  { name: "Cable Preacher Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine", "preacher bench"], description: "Cable preacher curl", muscleGroups: ["biceps"] },
  { name: "Single Arm Dumbbell Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbell"], description: "Single arm dumbbell curl", muscleGroups: ["biceps", "core"] },
  { name: "Single Arm Cable Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Single arm cable curl", muscleGroups: ["biceps", "core"] },
  { name: "Incline Hammer Curl", category: "biceps", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "incline bench"], description: "Incline hammer curl", muscleGroups: ["biceps"] },
  { name: "Decline Dumbbell Curl", category: "biceps", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "decline bench"], description: "Decline dumbbell curl", muscleGroups: ["biceps"] },
  { name: "Zottman Curl", category: "biceps", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells"], description: "Combined curl and reverse curl", muscleGroups: ["biceps", "forearms"] },
  { name: "Barbell Preacher Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["barbell", "preacher bench"], description: "Barbell preacher curl", muscleGroups: ["biceps"] },
  { name: "EZ Bar Preacher Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["EZ bar", "preacher bench"], description: "EZ bar preacher curl", muscleGroups: ["biceps"] },
  { name: "Machine Hammer Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine hammer curl", muscleGroups: ["biceps"] },
  { name: "Iso-Lateral Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Independent arm curl machine", muscleGroups: ["biceps"] },
  { name: "Lever Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Lever-based curl machine", muscleGroups: ["biceps"] },
  { name: "Plate Loaded Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Plate-loaded curl machine", muscleGroups: ["biceps"] },
  { name: "Cable Concentration Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable concentration curl", muscleGroups: ["biceps"] },
  { name: "Resistance Band Preacher Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["resistance band", "preacher bench"], description: "Band preacher curl", muscleGroups: ["biceps"] },
  { name: "Barbell Curl (Close Grip)", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Close grip barbell curl", muscleGroups: ["biceps"] },
  { name: "Barbell Curl (Wide Grip)", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Wide grip barbell curl", muscleGroups: ["biceps"] },
  { name: "Dumbbell Curl (Alternating)", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Alternating arm dumbbell curl", muscleGroups: ["biceps"] },
  { name: "Dumbbell Curl (Simultaneous)", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Both arms simultaneously", muscleGroups: ["biceps"] },
  { name: "Seated Dumbbell Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbells", "bench"], description: "Seated dumbbell curl", muscleGroups: ["biceps"] },
  { name: "Standing Cable Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Standing cable curl", muscleGroups: ["biceps"] },
  { name: "Seated Cable Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine", "bench"], description: "Seated cable curl", muscleGroups: ["biceps"] },
  { name: "Rope Cable Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Rope cable curl", muscleGroups: ["biceps"] },

  // ===== TRICEPS (45+ exercises) =====
  { name: "Barbell Bench Press Close Grip", category: "triceps", type: "compound", difficulty: "intermediate", equipment: ["barbell", "bench"], description: "Close grip bench for triceps", muscleGroups: ["triceps", "chest"] },
  { name: "Dumbbell Skull Crusher", category: "triceps", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "bench"], description: "Lying tricep extension", muscleGroups: ["triceps"] },
  { name: "Barbell Skull Crusher", category: "triceps", type: "isolation", difficulty: "intermediate", equipment: ["barbell", "bench"], description: "Barbell lying tricep extension", muscleGroups: ["triceps"] },
  { name: "EZ Bar Skull Crusher", category: "triceps", type: "isolation", difficulty: "intermediate", equipment: ["EZ bar", "bench"], description: "EZ bar tricep extension", muscleGroups: ["triceps"] },
  { name: "Tricep Dips", category: "triceps", type: "compound", difficulty: "intermediate", equipment: ["dip station"], description: "Bodyweight tricep dips", muscleGroups: ["triceps", "chest"] },
  { name: "Assisted Tricep Dips", category: "triceps", type: "compound", difficulty: "beginner", equipment: ["dip machine"], description: "Machine-assisted dips", muscleGroups: ["triceps", "chest"] },
  { name: "Tricep Rope Pushdown", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable rope tricep pushdown", muscleGroups: ["triceps"] },
  { name: "Tricep V-Bar Pushdown", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "V-bar tricep pushdown", muscleGroups: ["triceps"] },
  { name: "Tricep Bar Pushdown", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Straight bar tricep pushdown", muscleGroups: ["triceps"] },
  { name: "Overhead Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbell", "cable machine"], description: "Standing or seated overhead extension", muscleGroups: ["triceps"] },
  { name: "Dumbbell Overhead Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbell"], description: "Single arm overhead extension", muscleGroups: ["triceps"] },
  { name: "Cable Overhead Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable overhead extension", muscleGroups: ["triceps"] },
  { name: "Machine Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Guided tricep extension", muscleGroups: ["triceps"] },
  { name: "Tricep Kickback", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Single arm tricep kickback", muscleGroups: ["triceps"] },
  { name: "Cable Tricep Kickback", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable tricep kickback", muscleGroups: ["triceps"] },
  { name: "Bench Dips", category: "triceps", type: "compound", difficulty: "intermediate", equipment: ["bench"], description: "Bodyweight dips on bench", muscleGroups: ["triceps", "chest"] },
  { name: "Resistance Band Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band tricep extension", muscleGroups: ["triceps"] },
  { name: "Smith Machine Close Grip Press", category: "triceps", type: "compound", difficulty: "beginner", equipment: ["smith machine", "bench"], description: "Guided close grip press", muscleGroups: ["triceps", "chest"] },
  { name: "Machine Tricep Dip", category: "triceps", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine tricep dip", muscleGroups: ["triceps", "chest"] },
  { name: "Landmine Close Grip Press", category: "triceps", type: "compound", difficulty: "intermediate", equipment: ["landmine"], description: "Angled close grip press", muscleGroups: ["triceps", "chest"] },
  { name: "Dumbbell Close Grip Press", category: "triceps", type: "compound", difficulty: "intermediate", equipment: ["dumbbells", "bench"], description: "Close grip dumbbell press", muscleGroups: ["triceps", "chest"] },
  { name: "Single Arm Dumbbell Overhead Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbell"], description: "Single arm overhead extension", muscleGroups: ["triceps"] },
  { name: "Single Arm Cable Overhead Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Single arm cable overhead extension", muscleGroups: ["triceps"] },
  { name: "Incline Dumbbell Tricep Extension", category: "triceps", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "incline bench"], description: "Incline tricep extension", muscleGroups: ["triceps"] },
  { name: "Decline Dumbbell Tricep Extension", category: "triceps", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "decline bench"], description: "Decline tricep extension", muscleGroups: ["triceps"] },
  { name: "Tricep Pushdown (Rope)", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Rope pushdown", muscleGroups: ["triceps"] },
  { name: "Tricep Pushdown (Straight Bar)", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Straight bar pushdown", muscleGroups: ["triceps"] },
  { name: "Tricep Pushdown (V-Bar)", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "V-bar pushdown", muscleGroups: ["triceps"] },
  { name: "Tricep Pushdown (Angled Bar)", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Angled bar pushdown", muscleGroups: ["triceps"] },
  { name: "Machine Overhead Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine overhead extension", muscleGroups: ["triceps"] },
  { name: "Hammer Strength Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Hammer strength tricep extension", muscleGroups: ["triceps"] },
  { name: "Iso-Lateral Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Independent arm tricep extension", muscleGroups: ["triceps"] },
  { name: "Lever Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Lever-based tricep extension", muscleGroups: ["triceps"] },
  { name: "Plate Loaded Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Plate-loaded tricep extension", muscleGroups: ["triceps"] },
  { name: "Resistance Band Rope Pushdown", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band rope pushdown", muscleGroups: ["triceps"] },
  { name: "Dumbbell Tricep Kickback (Alternating)", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Alternating arm kickback", muscleGroups: ["triceps"] },
  { name: "Dumbbell Tricep Kickback (Simultaneous)", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Both arms simultaneously", muscleGroups: ["triceps"] },
  { name: "Single Arm Tricep Kickback", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbell"], description: "Single arm tricep kickback", muscleGroups: ["triceps"] },
  { name: "Weighted Tricep Dips", category: "triceps", type: "compound", difficulty: "advanced", equipment: ["dip station", "weight belt"], description: "Weighted dips", muscleGroups: ["triceps", "chest"] },
  { name: "Negative Tricep Dips", category: "triceps", type: "compound", difficulty: "intermediate", equipment: ["dip station"], description: "Eccentric-focused dips", muscleGroups: ["triceps", "chest"] },
  { name: "Tricep Dips (Feet Elevated)", category: "triceps", type: "compound", difficulty: "advanced", equipment: ["dip station"], description: "Dips with elevated feet", muscleGroups: ["triceps", "chest"] },
  { name: "Tricep Dips (Chest Lean)", category: "triceps", type: "compound", difficulty: "intermediate", equipment: ["dip station"], description: "Dips with chest lean", muscleGroups: ["triceps", "chest"] },
  { name: "Tricep Dips (Upright)", category: "triceps", type: "compound", difficulty: "intermediate", equipment: ["dip station"], description: "Upright dips", muscleGroups: ["triceps"] },
  { name: "Tricep Dips (Machine)", category: "triceps", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine-assisted dips", muscleGroups: ["triceps", "chest"] },
  { name: "Tricep Pushdown (Single Arm)", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Single arm pushdown", muscleGroups: ["triceps"] },
  { name: "Tricep Pushdown (Rope, Single Arm)", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Single arm rope pushdown", muscleGroups: ["triceps"] },

  // ===== FOREARMS (25+ exercises) =====
  { name: "Barbell Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Forearm flexor exercise", muscleGroups: ["forearms"] },
  { name: "Dumbbell Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell wrist curl", muscleGroups: ["forearms"] },
  { name: "Barbell Reverse Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Forearm extensor exercise", muscleGroups: ["forearms"] },
  { name: "Dumbbell Reverse Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell reverse wrist curl", muscleGroups: ["forearms"] },
  { name: "Cable Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable wrist curl", muscleGroups: ["forearms"] },
  { name: "Wrist Roller", category: "forearms", type: "isolation", difficulty: "intermediate", equipment: ["wrist roller"], description: "Wrist roller exercise", muscleGroups: ["forearms"] },
  { name: "Farmer's Carry", category: "forearms", type: "functional", difficulty: "beginner", equipment: ["dumbbells", "barbell"], description: "Grip strength and forearm endurance", muscleGroups: ["forearms", "grip"] },
  { name: "Plate Pinch", category: "forearms", type: "isolation", difficulty: "intermediate", equipment: ["weight plates"], description: "Grip strength exercise", muscleGroups: ["forearms", "grip"] },
  { name: "Dead Hang", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["pull-up bar"], description: "Grip endurance", muscleGroups: ["forearms", "grip"] },
  { name: "Zottman Curl", category: "forearms", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells"], description: "Combined curl and reverse curl", muscleGroups: ["biceps", "forearms"] },
  { name: "Reverse Barbell Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Barbell reverse curl", muscleGroups: ["forearms", "biceps"] },
  { name: "Reverse Dumbbell Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell reverse curl", muscleGroups: ["forearms", "biceps"] },
  { name: "Reverse Cable Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable reverse curl", muscleGroups: ["forearms", "biceps"] },
  { name: "Reverse Machine Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine reverse curl", muscleGroups: ["forearms", "biceps"] },
  { name: "Pronated Dumbbell Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Pronated grip dumbbell curl", muscleGroups: ["forearms", "biceps"] },
  { name: "Supinated Dumbbell Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Supinated grip dumbbell curl", muscleGroups: ["forearms", "biceps"] },
  { name: "Wrist Curl (Machine)", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine wrist curl", muscleGroups: ["forearms"] },
  { name: "Reverse Wrist Curl (Machine)", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine reverse wrist curl", muscleGroups: ["forearms"] },
  { name: "Cable Reverse Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable reverse wrist curl", muscleGroups: ["forearms"] },
  { name: "Resistance Band Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band wrist curl", muscleGroups: ["forearms"] },
  { name: "Resistance Band Reverse Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band reverse wrist curl", muscleGroups: ["forearms"] },
  { name: "Barbell Wrist Roller", category: "forearms", type: "isolation", difficulty: "intermediate", equipment: ["barbell", "wrist roller"], description: "Barbell wrist roller", muscleGroups: ["forearms"] },
  { name: "Dumbbell Wrist Roller", category: "forearms", type: "isolation", difficulty: "intermediate", equipment: ["dumbbell", "wrist roller"], description: "Dumbbell wrist roller", muscleGroups: ["forearms"] },
  { name: "Farmer's Carry (Uneven)", category: "forearms", type: "functional", difficulty: "intermediate", equipment: ["dumbbells"], description: "Uneven weight carry", muscleGroups: ["forearms", "grip", "core"] },
  { name: "Farmer's Carry (Heavy)", category: "forearms", type: "functional", difficulty: "advanced", equipment: ["dumbbells", "barbell"], description: "Heavy farmer's carry", muscleGroups: ["forearms", "grip"] },

  // ===== LEGS (60+ exercises) =====
  { name: "Barbell Back Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "King of leg exercises", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Barbell Front Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "Quad-focused squat", muscleGroups: ["quads", "core"] },
  { name: "Goblet Squat", category: "legs", type: "compound", difficulty: "beginner", equipment: ["dumbbell"], description: "Beginner-friendly squat", muscleGroups: ["quads", "glutes"] },
  { name: "Dumbbell Squat", category: "legs", type: "compound", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell squat variation", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Machine Leg Press", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Guided leg press", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Hack Squat", category: "legs", type: "compound", difficulty: "beginner", equipment: ["hack squat machine"], description: "Machine squat variation", muscleGroups: ["quads", "glutes"] },
  { name: "Smith Machine Squat", category: "legs", type: "compound", difficulty: "beginner", equipment: ["smith machine"], description: "Guided barbell squat", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Leg Extension", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Quad isolation", muscleGroups: ["quads"] },
  { name: "Leg Curl", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Hamstring isolation", muscleGroups: ["hamstrings"] },
  { name: "Lying Leg Curl", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Lying hamstring curl", muscleGroups: ["hamstrings"] },
  { name: "Seated Leg Curl", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Seated hamstring curl", muscleGroups: ["hamstrings"] },
  { name: "Standing Leg Curl", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Standing hamstring curl", muscleGroups: ["hamstrings"] },
  { name: "Leg Press", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine leg press", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Bulgarian Split Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["bench", "dumbbells"], description: "Single-leg squat variation", muscleGroups: ["quads", "glutes"] },
  { name: "Dumbbell Bulgarian Split Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["bench", "dumbbells"], description: "Dumbbell split squat", muscleGroups: ["quads", "glutes"] },
  { name: "Barbell Bulgarian Split Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["bench", "barbell"], description: "Barbell split squat", muscleGroups: ["quads", "glutes"] },
  { name: "Lunges", category: "legs", type: "compound", difficulty: "beginner", equipment: ["dumbbells"], description: "Walking or stationary lunges", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Barbell Lunges", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Barbell lunges", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Reverse Lunges", category: "legs", type: "compound", difficulty: "beginner", equipment: ["dumbbells"], description: "Reverse lunge variation", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Walking Lunges", category: "legs", type: "compound", difficulty: "beginner", equipment: ["dumbbells"], description: "Walking lunge variation", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Step-ups", category: "legs", type: "compound", difficulty: "beginner", equipment: ["bench", "dumbbells"], description: "Step-up exercise", muscleGroups: ["quads", "glutes"] },
  { name: "Box Jumps", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["box"], description: "Explosive leg power", muscleGroups: ["quads", "glutes", "calves"] },
  { name: "Jump Squats", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["bodyweight"], description: "Explosive squat variation", muscleGroups: ["quads", "glutes"] },
  { name: "Pistol Squat", category: "legs", type: "compound", difficulty: "advanced", equipment: ["bodyweight"], description: "Single-leg bodyweight squat", muscleGroups: ["quads", "glutes"] },
  { name: "Sissy Squat", category: "legs", type: "isolation", difficulty: "intermediate", equipment: ["bodyweight"], description: "Quad-focused squat", muscleGroups: ["quads"] },
  { name: "Hack Squat Machine", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine hack squat", muscleGroups: ["quads", "glutes"] },
  { name: "Pendulum Squat", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine pendulum squat", muscleGroups: ["quads", "glutes"] },
  { name: "V-Squat", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine V-squat", muscleGroups: ["quads", "glutes"] },
  { name: "Leg Press (45-degree)", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "45-degree leg press", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Leg Press (Horizontal)", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Horizontal leg press", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Leg Press (Vertical)", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Vertical leg press", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Single Leg Press", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["machine"], description: "Single leg leg press", muscleGroups: ["quads", "glutes", "hamstrings", "core"] },
  { name: "Single Leg Extension", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Single leg extension", muscleGroups: ["quads"] },
  { name: "Single Leg Curl", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Single leg curl", muscleGroups: ["hamstrings"] },
  { name: "Leg Extension (Machine)", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine leg extension", muscleGroups: ["quads"] },
  { name: "Leg Curl (Machine)", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine leg curl", muscleGroups: ["hamstrings"] },
  { name: "Leg Extension (Cable)", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable leg extension", muscleGroups: ["quads"] },
  { name: "Leg Curl (Cable)", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable leg curl", muscleGroups: ["hamstrings"] },
  { name: "Leg Extension (Resistance Band)", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band leg extension", muscleGroups: ["quads"] },
  { name: "Leg Curl (Resistance Band)", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band leg curl", muscleGroups: ["hamstrings"] },
  { name: "Calf Raise (Machine)", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine calf raise", muscleGroups: ["calves"] },
  { name: "Calf Raise (Barbell)", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Barbell calf raise", muscleGroups: ["calves"] },
  { name: "Calf Raise (Dumbbell)", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell calf raise", muscleGroups: ["calves"] },
  { name: "Calf Raise (Smith Machine)", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["smith machine"], description: "Smith machine calf raise", muscleGroups: ["calves"] },
  { name: "Seated Calf Raise", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine", "bench"], description: "Seated calf raise", muscleGroups: ["calves"] },
  { name: "Standing Calf Raise", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Standing calf raise", muscleGroups: ["calves"] },
  { name: "Leg Press Calf Raise", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Calf raise on leg press", muscleGroups: ["calves"] },
  { name: "Dumbbell Calf Raise", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell calf raise", muscleGroups: ["calves"] },
  { name: "Resistance Band Calf Raise", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band calf raise", muscleGroups: ["calves"] },
  { name: "Barbell Back Squat (High Bar)", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "High bar back squat", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Barbell Back Squat (Low Bar)", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "Low bar back squat", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Pause Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "Squat with pause", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Pin Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "Squat from pins", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Tempo Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "Squat with controlled tempo", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Deficit Squat", category: "legs", type: "compound", difficulty: "advanced", equipment: ["barbell", "squat rack"], description: "Squat from elevated position", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Box Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell", "box"], description: "Squat to box", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Dumbbell Step-ups", category: "legs", type: "compound", difficulty: "beginner", equipment: ["dumbbells", "bench"], description: "Dumbbell step-ups", muscleGroups: ["quads", "glutes"] },
  { name: "Barbell Step-ups", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell", "bench"], description: "Barbell step-ups", muscleGroups: ["quads", "glutes"] },
  { name: "Machine Step-ups", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine step-ups", muscleGroups: ["quads", "glutes"] },

  // ===== GLUTES (35+ exercises) =====
  { name: "Hip Thrust", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["bench", "barbell"], description: "Glute-focused hip thrust", muscleGroups: ["glutes"] },
  { name: "Barbell Hip Thrust", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["bench", "barbell"], description: "Barbell hip thrust", muscleGroups: ["glutes"] },
  { name: "Dumbbell Hip Thrust", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["bench", "dumbbell"], description: "Dumbbell hip thrust", muscleGroups: ["glutes"] },
  { name: "Machine Hip Thrust", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine hip thrust", muscleGroups: ["glutes"] },
  { name: "Single Leg Hip Thrust", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["bench", "barbell"], description: "Single-leg hip thrust", muscleGroups: ["glutes"] },
  { name: "Glute Bridge", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["bodyweight"], description: "Bodyweight glute bridge", muscleGroups: ["glutes"] },
  { name: "Barbell Glute Bridge", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["barbell"], description: "Barbell glute bridge", muscleGroups: ["glutes"] },
  { name: "Cable Pull-through", category: "glutes", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Glute isolation exercise", muscleGroups: ["glutes"] },
  { name: "Machine Glute Kickback", category: "glutes", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine glute kickback", muscleGroups: ["glutes"] },
  { name: "Cable Glute Kickback", category: "glutes", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable glute kickback", muscleGroups: ["glutes"] },
  { name: "Dumbbell Glute Kickback", category: "glutes", type: "isolation", difficulty: "beginner", equipment: ["dumbbell"], description: "Dumbbell glute kickback", muscleGroups: ["glutes"] },
  { name: "Smith Machine Hip Thrust", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["smith machine", "bench"], description: "Smith machine hip thrust", muscleGroups: ["glutes"] },
  { name: "Leg Press (Glute Focus)", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Leg press with glute focus", muscleGroups: ["glutes", "quads"] },
  { name: "V-Squat", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine V-squat", muscleGroups: ["glutes", "quads"] },
  { name: "Smith Machine Glute Bridge", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["smith machine"], description: "Smith machine glute bridge", muscleGroups: ["glutes"] },
  { name: "Resistance Band Glute Bridge", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["resistance band"], description: "Band glute bridge", muscleGroups: ["glutes"] },
  { name: "Resistance Band Hip Thrust", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["resistance band", "bench"], description: "Band hip thrust", muscleGroups: ["glutes"] },
  { name: "Resistance Band Glute Kickback", category: "glutes", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band glute kickback", muscleGroups: ["glutes"] },
  { name: "Glute Kickback (Machine)", category: "glutes", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine glute kickback", muscleGroups: ["glutes"] },
  { name: "Glute Kickback (Cable)", category: "glutes", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable glute kickback", muscleGroups: ["glutes"] },
  { name: "Single Leg Glute Bridge", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["bodyweight"], description: "Single-leg glute bridge", muscleGroups: ["glutes"] },
  { name: "Weighted Glute Bridge", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Weighted glute bridge", muscleGroups: ["glutes"] },
  { name: "Pause Hip Thrust", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["bench", "barbell"], description: "Hip thrust with pause", muscleGroups: ["glutes"] },
  { name: "Tempo Hip Thrust", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["bench", "barbell"], description: "Hip thrust with controlled tempo", muscleGroups: ["glutes"] },
  { name: "Deficit Hip Thrust", category: "glutes", type: "compound", difficulty: "advanced", equipment: ["bench", "barbell"], description: "Hip thrust from elevated position", muscleGroups: ["glutes"] },
  { name: "Elevated Hip Thrust", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["bench", "barbell"], description: "Hip thrust with elevated feet", muscleGroups: ["glutes"] },
  { name: "Machine Leg Press (Glute Focus)", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine leg press with glute focus", muscleGroups: ["glutes"] },
  { name: "Hack Squat (Glute Focus)", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Hack squat with glute focus", muscleGroups: ["glutes"] },
  { name: "Pendulum Squat (Glute Focus)", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Pendulum squat with glute focus", muscleGroups: ["glutes"] },
  { name: "Barbell Back Squat (Glute Focus)", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "Back squat with glute focus", muscleGroups: ["glutes"] },
  { name: "Bulgarian Split Squat (Glute Focus)", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["bench", "dumbbells"], description: "Split squat with glute focus", muscleGroups: ["glutes"] },
  { name: "Dumbbell Glute Bridge", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["dumbbell"], description: "Dumbbell glute bridge", muscleGroups: ["glutes"] },
  { name: "Landmine Hip Thrust", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["landmine", "bench"], description: "Landmine hip thrust", muscleGroups: ["glutes"] },
  { name: "Trap Bar Hip Thrust", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["trap bar", "bench"], description: "Trap bar hip thrust", muscleGroups: ["glutes"] },
  { name: "Sumo Squat (Glute Focus)", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "Sumo squat with glute focus", muscleGroups: ["glutes"] },

  // ===== CORE (40+ exercises) =====
  { name: "Plank", category: "core", type: "isolation", difficulty: "beginner", equipment: ["bodyweight"], description: "Isometric core hold", muscleGroups: ["core"] },
  { name: "Side Plank", category: "core", type: "isolation", difficulty: "beginner", equipment: ["bodyweight"], description: "Side core hold", muscleGroups: ["obliques", "core"] },
  { name: "Ab Wheel Rollout", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["ab wheel"], description: "Advanced core exercise", muscleGroups: ["abs", "core"] },
  { name: "Cable Crunch", category: "core", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable ab crunch", muscleGroups: ["abs"] },
  { name: "Machine Crunch", category: "core", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine ab crunch", muscleGroups: ["abs"] },
  { name: "Decline Sit-ups", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["decline bench"], description: "Decline ab sit-ups", muscleGroups: ["abs"] },
  { name: "Weighted Sit-ups", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["weight plate"], description: "Weighted sit-ups", muscleGroups: ["abs"] },
  { name: "Hanging Leg Raises", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["pull-up bar"], description: "Hanging leg raise", muscleGroups: ["abs", "core"] },
  { name: "Lying Leg Raises", category: "core", type: "isolation", difficulty: "beginner", equipment: ["bench"], description: "Lying leg raise", muscleGroups: ["abs", "core"] },
  { name: "Machine Ab Crunch", category: "core", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine ab crunch", muscleGroups: ["abs"] },
  { name: "Pallof Press", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["cable machine"], description: "Anti-rotation core exercise", muscleGroups: ["obliques", "core"] },
  { name: "Landmine Rotation", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["landmine"], description: "Rotational core exercise", muscleGroups: ["obliques", "core"] },
  { name: "Russian Twist", category: "core", type: "isolation", difficulty: "beginner", equipment: ["weight plate"], description: "Oblique twist exercise", muscleGroups: ["obliques"] },
  { name: "Suitcase Carry", category: "core", type: "functional", difficulty: "beginner", equipment: ["dumbbell"], description: "Unilateral core stability", muscleGroups: ["obliques", "core"] },
  { name: "Dead Bug", category: "core", type: "isolation", difficulty: "beginner", equipment: ["bodyweight"], description: "Core stability exercise", muscleGroups: ["core"] },
  { name: "Bird Dog", category: "core", type: "isolation", difficulty: "beginner", equipment: ["bodyweight"], description: "Core stability exercise", muscleGroups: ["core"] },
  { name: "Ab Coaster", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["ab coaster"], description: "Ab coaster machine", muscleGroups: ["abs"] },
  { name: "Decline Crunch", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["decline bench"], description: "Decline ab crunch", muscleGroups: ["abs"] },
  { name: "Barbell Rollout", category: "core", type: "isolation", difficulty: "advanced", equipment: ["barbell"], description: "Barbell core rollout", muscleGroups: ["abs", "core"] },
  { name: "Dumbbell Rollout", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["dumbbell"], description: "Dumbbell core rollout", muscleGroups: ["abs", "core"] },
  { name: "Stability Ball Crunch", category: "core", type: "isolation", difficulty: "beginner", equipment: ["stability ball"], description: "Stability ball crunch", muscleGroups: ["abs"] },
  { name: "Stability Ball Rollout", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["stability ball"], description: "Stability ball rollout", muscleGroups: ["abs", "core"] },
  { name: "Cable Woodchop", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["cable machine"], description: "Rotational core exercise", muscleGroups: ["obliques", "core"] },
  { name: "Landmine Woodchop", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["landmine"], description: "Rotational core exercise", muscleGroups: ["obliques", "core"] },
  { name: "Dumbbell Woodchop", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["dumbbell"], description: "Rotational core exercise", muscleGroups: ["obliques", "core"] },
  { name: "Medicine Ball Slam", category: "core", type: "functional", difficulty: "intermediate", equipment: ["medicine ball"], description: "Explosive core exercise", muscleGroups: ["abs", "core"] },
  { name: "Medicine Ball Chest Pass", category: "core", type: "functional", difficulty: "intermediate", equipment: ["medicine ball"], description: "Explosive core exercise", muscleGroups: ["abs", "core"] },
  { name: "Weighted Plank", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["weight plate"], description: "Weighted plank", muscleGroups: ["core"] },
  { name: "Weighted Side Plank", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["weight plate"], description: "Weighted side plank", muscleGroups: ["obliques", "core"] },
  { name: "Ab Wheel (Kneeling)", category: "core", type: "isolation", difficulty: "beginner", equipment: ["ab wheel"], description: "Kneeling ab wheel", muscleGroups: ["abs", "core"] },
  { name: "Ab Wheel (Standing)", category: "core", type: "isolation", difficulty: "advanced", equipment: ["ab wheel"], description: "Standing ab wheel", muscleGroups: ["abs", "core"] },
  { name: "Hanging Knee Raises", category: "core", type: "isolation", difficulty: "beginner", equipment: ["pull-up bar"], description: "Hanging knee raise", muscleGroups: ["abs", "core"] },
  { name: "Hanging Tuck", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["pull-up bar"], description: "Hanging tuck", muscleGroups: ["abs", "core"] },
  { name: "Hanging L-Sit", category: "core", type: "isolation", difficulty: "advanced", equipment: ["pull-up bar"], description: "Hanging L-sit", muscleGroups: ["abs", "core"] },
  { name: "Decline Leg Raises", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["decline bench"], description: "Decline leg raise", muscleGroups: ["abs", "core"] },
  { name: "Machine Ab Crunch (Single Arm)", category: "core", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Single arm machine crunch", muscleGroups: ["abs"] },
  { name: "Cable Crunch (Single Arm)", category: "core", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Single arm cable crunch", muscleGroups: ["abs"] },
  { name: "Landmine Rotation (Single Arm)", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["landmine"], description: "Single arm landmine rotation", muscleGroups: ["obliques", "core"] },
  { name: "Pallof Press (Single Arm)", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["cable machine"], description: "Single arm pallof press", muscleGroups: ["obliques", "core"] },
  { name: "Ab Coaster (Machine)", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["machine"], description: "Machine ab coaster", muscleGroups: ["abs"] },

  // ===== CARDIO (30+ exercises) =====
  { name: "Treadmill Running", category: "cardio", type: "cardio", difficulty: "beginner", equipment: ["treadmill"], description: "Steady-state cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Incline Treadmill Walking", category: "cardio", type: "cardio", difficulty: "beginner", equipment: ["treadmill"], description: "Low-impact cardio", muscleGroups: ["legs", "glutes"] },
  { name: "Stationary Bike", category: "cardio", type: "cardio", difficulty: "beginner", equipment: ["stationary bike"], description: "Low-impact leg cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Rowing Machine", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["rowing machine"], description: "Full-body cardio", muscleGroups: ["back", "legs", "cardio"] },
  { name: "Elliptical Machine", category: "cardio", type: "cardio", difficulty: "beginner", equipment: ["elliptical"], description: "Low-impact full-body cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Stair Climber", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["stair climber"], description: "Intense leg cardio", muscleGroups: ["legs", "glutes", "cardio"] },
  { name: "Jump Rope", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["jump rope"], description: "Explosive cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Burpees", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["bodyweight"], description: "Full-body explosive cardio", muscleGroups: ["cardio", "core", "chest"] },
  { name: "Mountain Climbers", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["bodyweight"], description: "Core and cardio", muscleGroups: ["core", "cardio"] },
  { name: "Battle Ropes", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["battle ropes"], description: "Explosive cardio", muscleGroups: ["shoulders", "cardio"] },
  { name: "Sled Push", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["sled"], description: "Explosive leg cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Sled Pull", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["sled"], description: "Explosive leg cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Assault Bike", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["assault bike"], description: "High-intensity cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Swimming", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["pool"], description: "Full-body low-impact cardio", muscleGroups: ["cardio", "back", "shoulders"] },
  { name: "Sprints", category: "cardio", type: "cardio", difficulty: "advanced", equipment: ["bodyweight"], description: "High-intensity running", muscleGroups: ["legs", "cardio"] },
  { name: "Agility Ladder", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["agility ladder"], description: "Footwork and agility", muscleGroups: ["legs", "cardio"] },
  { name: "Box Sprints", category: "cardio", type: "cardio", difficulty: "advanced", equipment: ["box"], description: "Explosive sprint training", muscleGroups: ["legs", "cardio"] },
  { name: "Sled Drag", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["sled"], description: "Leg endurance", muscleGroups: ["legs", "cardio"] },
  { name: "Prowler Push", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["prowler"], description: "Explosive leg power", muscleGroups: ["legs", "cardio"] },
  { name: "Prowler Drag", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["prowler"], description: "Explosive leg power", muscleGroups: ["legs", "cardio"] },
  { name: "Tire Flip", category: "cardio", type: "functional", difficulty: "advanced", equipment: ["tire"], description: "Full-body explosive power", muscleGroups: ["back", "legs", "cardio"] },
  { name: "Rope Climb", category: "cardio", type: "functional", difficulty: "advanced", equipment: ["rope"], description: "Full-body pulling power", muscleGroups: ["back", "arms", "core"] },
  { name: "Wall Ball", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["medicine ball"], description: "Explosive power", muscleGroups: ["legs", "shoulders", "cardio"] },
  { name: "Treadmill Incline Sprint", category: "cardio", type: "cardio", difficulty: "advanced", equipment: ["treadmill"], description: "High-intensity incline running", muscleGroups: ["legs", "glutes", "cardio"] },
  { name: "Bike Sprint", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["stationary bike"], description: "High-intensity bike sprint", muscleGroups: ["legs", "cardio"] },
  { name: "Rowing Sprint", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["rowing machine"], description: "High-intensity rowing", muscleGroups: ["back", "legs", "cardio"] },
  { name: "Elliptical Sprint", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["elliptical"], description: "High-intensity elliptical", muscleGroups: ["legs", "cardio"] },
  { name: "Stair Climber Sprint", category: "cardio", type: "cardio", difficulty: "advanced", equipment: ["stair climber"], description: "High-intensity stair climbing", muscleGroups: ["legs", "glutes", "cardio"] },
  { name: "Assault Bike Sprint", category: "cardio", type: "cardio", difficulty: "advanced", equipment: ["assault bike"], description: "High-intensity assault bike", muscleGroups: ["legs", "cardio"] },
  { name: "Swimming Sprints", category: "cardio", type: "cardio", difficulty: "advanced", equipment: ["pool"], description: "High-intensity swimming", muscleGroups: ["cardio", "back", "shoulders"] },

  // ===== FUNCTIONAL (30+ exercises) =====
  { name: "Farmer's Carry", category: "functional", type: "functional", difficulty: "beginner", equipment: ["dumbbells"], description: "Grip and core strength", muscleGroups: ["forearms", "core"] },
  { name: "Sandbag Carry", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["sandbag"], description: "Unbalanced load carry", muscleGroups: ["core", "grip"] },
  { name: "Kettlebell Swing", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["kettlebell"], description: "Explosive hip drive", muscleGroups: ["glutes", "hamstrings", "cardio"] },
  { name: "Kettlebell Turkish Get-up", category: "functional", type: "functional", difficulty: "advanced", equipment: ["kettlebell"], description: "Full-body mobility and strength", muscleGroups: ["shoulders", "core", "glutes"] },
  { name: "Medicine Ball Slam", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["medicine ball"], description: "Explosive power", muscleGroups: ["shoulders", "core", "cardio"] },
  { name: "Medicine Ball Chest Pass", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["medicine ball"], description: "Explosive chest power", muscleGroups: ["chest", "shoulders", "cardio"] },
  { name: "Tire Flip", category: "functional", type: "functional", difficulty: "advanced", equipment: ["tire"], description: "Full-body explosive power", muscleGroups: ["back", "legs", "cardio"] },
  { name: "Prowler Push", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["prowler"], description: "Explosive leg power", muscleGroups: ["legs", "cardio"] },
  { name: "Prowler Drag", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["prowler"], description: "Explosive leg power", muscleGroups: ["legs", "cardio"] },
  { name: "Sled Drag", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["sled"], description: "Leg endurance", muscleGroups: ["legs", "cardio"] },
  { name: "Rope Climb", category: "functional", type: "functional", difficulty: "advanced", equipment: ["rope"], description: "Full-body pulling power", muscleGroups: ["back", "arms", "core"] },
  { name: "Wall Ball", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["medicine ball"], description: "Explosive power", muscleGroups: ["legs", "shoulders", "cardio"] },
  { name: "Burpees", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["bodyweight"], description: "Full-body explosive cardio", muscleGroups: ["cardio", "core", "chest"] },
  { name: "Mountain Climbers", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["bodyweight"], description: "Core and cardio", muscleGroups: ["core", "cardio"] },
  { name: "Battle Ropes", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["battle ropes"], description: "Explosive cardio", muscleGroups: ["shoulders", "cardio"] },
  { name: "Sled Push", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["sled"], description: "Explosive leg power", muscleGroups: ["legs", "cardio"] },
  { name: "Sled Pull", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["sled"], description: "Explosive leg power", muscleGroups: ["legs", "cardio"] },
  { name: "Agility Ladder", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["agility ladder"], description: "Footwork and agility", muscleGroups: ["legs", "cardio"] },
  { name: "Box Sprints", category: "functional", type: "functional", difficulty: "advanced", equipment: ["box"], description: "Explosive sprint training", muscleGroups: ["legs", "cardio"] },
  { name: "Kettlebell Snatch", category: "functional", type: "functional", difficulty: "advanced", equipment: ["kettlebell"], description: "Full-body explosive power", muscleGroups: ["shoulders", "back", "legs"] },
  { name: "Kettlebell Clean", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["kettlebell"], description: "Full-body power", muscleGroups: ["shoulders", "back", "legs"] },
  { name: "Kettlebell Press", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["kettlebell"], description: "Shoulder and core power", muscleGroups: ["shoulders", "core"] },
  { name: "Kettlebell Goblet Squat", category: "functional", type: "functional", difficulty: "beginner", equipment: ["kettlebell"], description: "Leg and core exercise", muscleGroups: ["legs", "core"] },
  { name: "Sandbag Throw", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["sandbag"], description: "Explosive power", muscleGroups: ["shoulders", "core"] },
  { name: "Sandbag Clean", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["sandbag"], description: "Full-body power", muscleGroups: ["shoulders", "back", "legs"] },
  { name: "Sandbag Squat", category: "functional", type: "functional", difficulty: "beginner", equipment: ["sandbag"], description: "Leg and core exercise", muscleGroups: ["legs", "core"] },
  { name: "Sandbag Shoulder Press", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["sandbag"], description: "Shoulder and core exercise", muscleGroups: ["shoulders", "core"] },
  { name: "Landmine Rotation", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["landmine"], description: "Rotational core exercise", muscleGroups: ["obliques", "core"] },
  { name: "Landmine Press", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["landmine"], description: "Full-body pressing", muscleGroups: ["shoulders", "chest", "core"] },
  { name: "Landmine Squat", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["landmine"], description: "Leg and core exercise", muscleGroups: ["legs", "core"] },
];

export const MUSCLE_GROUPS = [
  "chest",
  "back",
  "shoulders",
  "biceps",
  "triceps",
  "forearms",
  "quads",
  "hamstrings",
  "glutes",
  "calves",
  "core",
  "abs",
  "obliques",
  "lats",
  "traps",
  "rear delts",
  "front delts",
  "lateral delts",
  "upper chest",
  "lower chest",
  "upper back",
  "grip",
  "cardio",
];

export const EXERCISE_CATEGORIES = ["chest", "back", "shoulders", "biceps", "triceps", "forearms", "legs", "glutes", "core", "cardio", "functional"];
