/**
 * Comprehensive Exercise Database
 * 200+ exercises covering all lifting categories
 * Reference: StrongApp, MyFitnessPal, Fitbod, JEFIT
 */

export interface Exercise {
  name: string;
  category: "chest" | "back" | "shoulders" | "biceps" | "triceps" | "forearms" | "legs" | "glutes" | "core" | "cardio" | "functional";
  type: "compound" | "isolation" | "cardio" | "functional";
  difficulty: "beginner" | "intermediate" | "advanced";
  equipment: string[];
  description: string;
  muscleGroups: string[];
}

export const EXERCISES: Exercise[] = [
  // ===== CHEST =====
  { name: "Barbell Bench Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["barbell", "bench"], description: "Classic horizontal pressing movement", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Dumbbell Bench Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["dumbbells", "bench"], description: "Pressing with dumbbells for greater range of motion", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Incline Barbell Bench Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["barbell", "incline bench"], description: "Emphasizes upper chest", muscleGroups: ["upper chest", "shoulders", "triceps"] },
  { name: "Incline Dumbbell Bench Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["dumbbells", "incline bench"], description: "Dumbbell variation for upper chest", muscleGroups: ["upper chest", "shoulders", "triceps"] },
  { name: "Decline Barbell Bench Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["barbell", "decline bench"], description: "Emphasizes lower chest", muscleGroups: ["lower chest", "triceps"] },
  { name: "Decline Dumbbell Bench Press", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["dumbbells", "decline bench"], description: "Dumbbell variation for lower chest", muscleGroups: ["lower chest", "triceps"] },
  { name: "Machine Chest Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Guided chest press on machine", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Chest Fly Machine", category: "chest", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Isolates chest with guided motion", muscleGroups: ["chest"] },
  { name: "Dumbbell Chest Fly", category: "chest", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "bench"], description: "Free-weight chest fly for isolation", muscleGroups: ["chest"] },
  { name: "Cable Chest Fly", category: "chest", type: "isolation", difficulty: "intermediate", equipment: ["cable machine"], description: "Chest fly with cables", muscleGroups: ["chest"] },
  { name: "Push-ups", category: "chest", type: "compound", difficulty: "beginner", equipment: ["bodyweight"], description: "Bodyweight chest pressing", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Incline Push-ups", category: "chest", type: "compound", difficulty: "beginner", equipment: ["bodyweight"], description: "Easier variation of push-ups", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Decline Push-ups", category: "chest", type: "compound", difficulty: "advanced", equipment: ["bodyweight"], description: "Harder variation emphasizing upper chest", muscleGroups: ["upper chest", "triceps", "shoulders"] },
  { name: "Wide Grip Push-ups", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["bodyweight"], description: "Wider hand placement for chest emphasis", muscleGroups: ["chest", "shoulders"] },
  { name: "Close Grip Push-ups", category: "chest", type: "compound", difficulty: "intermediate", equipment: ["bodyweight"], description: "Narrower hand placement for triceps emphasis", muscleGroups: ["triceps", "chest"] },
  { name: "Plyometric Push-ups", category: "chest", type: "compound", difficulty: "advanced", equipment: ["bodyweight"], description: "Explosive push-ups for power", muscleGroups: ["chest", "triceps", "shoulders"] },
  { name: "Pec Deck Machine", category: "chest", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine-guided pec isolation", muscleGroups: ["chest"] },
  { name: "Resistance Band Chest Press", category: "chest", type: "compound", difficulty: "beginner", equipment: ["resistance band"], description: "Chest press with bands", muscleGroups: ["chest", "triceps", "shoulders"] },

  // ===== BACK =====
  { name: "Barbell Deadlift", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "King of back exercises", muscleGroups: ["back", "glutes", "hamstrings", "core"] },
  { name: "Sumo Deadlift", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Wide stance deadlift", muscleGroups: ["back", "glutes", "quads", "core"] },
  { name: "Romanian Deadlift", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Hip hinge movement for posterior chain", muscleGroups: ["hamstrings", "back", "glutes"] },
  { name: "Trap Bar Deadlift", category: "back", type: "compound", difficulty: "intermediate", equipment: ["trap bar"], description: "Deadlift with trap bar", muscleGroups: ["back", "glutes", "quads"] },
  { name: "Dumbbell Deadlift", category: "back", type: "compound", difficulty: "intermediate", equipment: ["dumbbells"], description: "Deadlift variation with dumbbells", muscleGroups: ["back", "glutes", "hamstrings"] },
  { name: "Barbell Bent Over Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Classic horizontal pulling", muscleGroups: ["back", "biceps"] },
  { name: "Dumbbell Bent Over Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["dumbbells"], description: "Single or double arm bent over row", muscleGroups: ["back", "biceps"] },
  { name: "Pendlay Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Chest-supported row variation", muscleGroups: ["back", "biceps"] },
  { name: "Chest Supported Row Machine", category: "back", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Guided row with chest support", muscleGroups: ["back", "biceps"] },
  { name: "T-Bar Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Angled row with barbell", muscleGroups: ["back", "biceps"] },
  { name: "Seal Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell", "bench"], description: "Chest-supported row on bench", muscleGroups: ["back", "biceps"] },
  { name: "Machine Row", category: "back", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Guided horizontal pulling", muscleGroups: ["back", "biceps"] },
  { name: "Cable Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["cable machine"], description: "Seated or standing cable row", muscleGroups: ["back", "biceps"] },
  { name: "Lat Pulldown", category: "back", type: "compound", difficulty: "beginner", equipment: ["cable machine"], description: "Vertical pulling movement", muscleGroups: ["lats", "biceps"] },
  { name: "Wide Grip Lat Pulldown", category: "back", type: "compound", difficulty: "beginner", equipment: ["cable machine"], description: "Wide grip for lat emphasis", muscleGroups: ["lats", "back"] },
  { name: "Close Grip Lat Pulldown", category: "back", type: "compound", difficulty: "beginner", equipment: ["cable machine"], description: "Close grip for biceps emphasis", muscleGroups: ["lats", "biceps"] },
  { name: "Reverse Grip Lat Pulldown", category: "back", type: "compound", difficulty: "beginner", equipment: ["cable machine"], description: "Underhand grip lat pulldown", muscleGroups: ["lats", "biceps"] },
  { name: "Pull-ups", category: "back", type: "compound", difficulty: "intermediate", equipment: ["pull-up bar"], description: "Bodyweight vertical pulling", muscleGroups: ["lats", "back", "biceps"] },
  { name: "Chin-ups", category: "back", type: "compound", difficulty: "intermediate", equipment: ["pull-up bar"], description: "Underhand grip pull-ups", muscleGroups: ["lats", "biceps"] },
  { name: "Wide Grip Pull-ups", category: "back", type: "compound", difficulty: "advanced", equipment: ["pull-up bar"], description: "Wide grip for lat emphasis", muscleGroups: ["lats", "back"] },
  { name: "Assisted Pull-ups", category: "back", type: "compound", difficulty: "beginner", equipment: ["pull-up machine"], description: "Machine-assisted pull-ups", muscleGroups: ["lats", "back", "biceps"] },
  { name: "Resistance Band Pull-ups", category: "back", type: "compound", difficulty: "beginner", equipment: ["pull-up bar", "resistance band"], description: "Band-assisted pull-ups", muscleGroups: ["lats", "back", "biceps"] },
  { name: "Negative Pull-ups", category: "back", type: "compound", difficulty: "intermediate", equipment: ["pull-up bar"], description: "Eccentric-focused pull-ups", muscleGroups: ["lats", "back", "biceps"] },
  { name: "Single Arm Lat Pulldown", category: "back", type: "isolation", difficulty: "intermediate", equipment: ["cable machine"], description: "Unilateral lat work", muscleGroups: ["lats"] },
  { name: "Straight Arm Lat Pulldown", category: "back", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Isolation for lats", muscleGroups: ["lats"] },
  { name: "Face Pulls", category: "back", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Rear delt and upper back exercise", muscleGroups: ["rear delts", "upper back"] },
  { name: "Reverse Pec Deck", category: "back", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine isolation for rear delts", muscleGroups: ["rear delts", "back"] },
  { name: "Back Hyperextension", category: "back", type: "isolation", difficulty: "intermediate", equipment: ["hyperextension bench"], description: "Lower back and glute exercise", muscleGroups: ["lower back", "glutes"] },
  { name: "Good Mornings", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Posterior chain exercise", muscleGroups: ["hamstrings", "back", "glutes"] },
  { name: "Shrugs", category: "back", type: "isolation", difficulty: "beginner", equipment: ["barbell", "dumbbells"], description: "Trapezius isolation", muscleGroups: ["traps"] },
  { name: "Upright Row", category: "back", type: "compound", difficulty: "intermediate", equipment: ["barbell", "dumbbells"], description: "Vertical pulling for traps and shoulders", muscleGroups: ["traps", "shoulders"] },

  // ===== SHOULDERS =====
  { name: "Barbell Overhead Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Standing shoulder press", muscleGroups: ["shoulders", "triceps", "core"] },
  { name: "Dumbbell Shoulder Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["dumbbells", "bench"], description: "Seated or standing dumbbell press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Machine Shoulder Press", category: "shoulders", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Guided shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Pike Push-ups", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["bodyweight"], description: "Bodyweight shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Handstand Push-ups", category: "shoulders", type: "compound", difficulty: "advanced", equipment: ["bodyweight"], description: "Advanced bodyweight shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Shoulder width isolation", muscleGroups: ["lateral delts"] },
  { name: "Cable Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable lateral raise", muscleGroups: ["lateral delts"] },
  { name: "Machine Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine-guided lateral raise", muscleGroups: ["lateral delts"] },
  { name: "Front Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["dumbbells", "barbell"], description: "Front delt isolation", muscleGroups: ["front delts"] },
  { name: "Plate Front Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["weight plate"], description: "Front raise with plate", muscleGroups: ["front delts"] },
  { name: "Reverse Pec Deck Fly", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Rear delt isolation", muscleGroups: ["rear delts"] },
  { name: "Dumbbell Reverse Fly", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Rear delt fly with dumbbells", muscleGroups: ["rear delts"] },
  { name: "Cable Reverse Fly", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable rear delt fly", muscleGroups: ["rear delts"] },
  { name: "Arnold Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["dumbbells"], description: "Rotational shoulder press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Landmine Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["landmine"], description: "Angled barbell press", muscleGroups: ["shoulders", "triceps"] },
  { name: "Incline Dumbbell Press", category: "shoulders", type: "compound", difficulty: "intermediate", equipment: ["dumbbells", "incline bench"], description: "Incline pressing for shoulders", muscleGroups: ["shoulders", "chest", "triceps"] },
  { name: "Machine Lateral Raise", category: "shoulders", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine lateral raise", muscleGroups: ["lateral delts"] },

  // ===== BICEPS =====
  { name: "Barbell Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Classic bicep curl", muscleGroups: ["biceps"] },
  { name: "Dumbbell Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Single or double arm dumbbell curl", muscleGroups: ["biceps"] },
  { name: "Machine Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Guided bicep curl", muscleGroups: ["biceps"] },
  { name: "Cable Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable bicep curl", muscleGroups: ["biceps"] },
  { name: "EZ Bar Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["EZ bar"], description: "Easier on wrists than straight bar", muscleGroups: ["biceps"] },
  { name: "Preacher Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["preacher bench", "barbell"], description: "Isolated curl on preacher bench", muscleGroups: ["biceps"] },
  { name: "Incline Dumbbell Curl", category: "biceps", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "incline bench"], description: "Greater range of motion curl", muscleGroups: ["biceps"] },
  { name: "Concentration Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbell"], description: "Seated single-arm curl", muscleGroups: ["biceps"] },
  { name: "Hammer Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Neutral grip curl", muscleGroups: ["biceps", "forearms"] },
  { name: "Cable Hammer Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable hammer curl", muscleGroups: ["biceps", "forearms"] },
  { name: "Reverse Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["barbell", "dumbbells"], description: "Overhand grip curl for forearms", muscleGroups: ["biceps", "forearms"] },
  { name: "Barbell Reverse Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Barbell reverse curl", muscleGroups: ["biceps", "forearms"] },
  { name: "Resistance Band Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band bicep curl", muscleGroups: ["biceps"] },
  { name: "21s Curl", category: "biceps", type: "isolation", difficulty: "intermediate", equipment: ["barbell", "dumbbells"], description: "Advanced curl technique", muscleGroups: ["biceps"] },
  { name: "Drag Curl", category: "biceps", type: "isolation", difficulty: "intermediate", equipment: ["barbell", "dumbbells"], description: "Curl with elbow drag", muscleGroups: ["biceps"] },
  { name: "Machine Preacher Curl", category: "biceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine preacher curl", muscleGroups: ["biceps"] },

  // ===== TRICEPS =====
  { name: "Barbell Bench Press Close Grip", category: "triceps", type: "compound", difficulty: "intermediate", equipment: ["barbell", "bench"], description: "Close grip bench for triceps", muscleGroups: ["triceps", "chest"] },
  { name: "Dumbbell Skull Crusher", category: "triceps", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells", "bench"], description: "Lying tricep extension", muscleGroups: ["triceps"] },
  { name: "Barbell Skull Crusher", category: "triceps", type: "isolation", difficulty: "intermediate", equipment: ["barbell", "bench"], description: "Barbell lying tricep extension", muscleGroups: ["triceps"] },
  { name: "EZ Bar Skull Crusher", category: "triceps", type: "isolation", difficulty: "intermediate", equipment: ["EZ bar", "bench"], description: "EZ bar tricep extension", muscleGroups: ["triceps"] },
  { name: "Tricep Dips", category: "triceps", type: "compound", difficulty: "intermediate", equipment: ["dip station"], description: "Bodyweight tricep dips", muscleGroups: ["triceps", "chest"] },
  { name: "Assisted Tricep Dips", category: "triceps", type: "compound", difficulty: "beginner", equipment: ["dip machine"], description: "Machine-assisted dips", muscleGroups: ["triceps", "chest"] },
  { name: "Tricep Rope Pushdown", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable rope tricep pushdown", muscleGroups: ["triceps"] },
  { name: "Tricep V-Bar Pushdown", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "V-bar tricep pushdown", muscleGroups: ["triceps"] },
  { name: "Tricep Bar Pushdown", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Straight bar tricep pushdown", muscleGroups: ["triceps"] },
  { name: "Overhead Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbell", "cable machine"], description: "Standing or seated overhead extension", muscleGroups: ["triceps"] },
  { name: "Dumbbell Overhead Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbell"], description: "Single arm overhead extension", muscleGroups: ["triceps"] },
  { name: "Cable Overhead Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable overhead extension", muscleGroups: ["triceps"] },
  { name: "Machine Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Guided tricep extension", muscleGroups: ["triceps"] },
  { name: "Tricep Kickback", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Single arm tricep kickback", muscleGroups: ["triceps"] },
  { name: "Cable Tricep Kickback", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable tricep kickback", muscleGroups: ["triceps"] },
  { name: "Bench Dips", category: "triceps", type: "compound", difficulty: "intermediate", equipment: ["bench"], description: "Bodyweight dips on bench", muscleGroups: ["triceps", "chest"] },
  { name: "Resistance Band Tricep Extension", category: "triceps", type: "isolation", difficulty: "beginner", equipment: ["resistance band"], description: "Band tricep extension", muscleGroups: ["triceps"] },

  // ===== FOREARMS =====
  { name: "Barbell Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Forearm flexor exercise", muscleGroups: ["forearms"] },
  { name: "Dumbbell Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell wrist curl", muscleGroups: ["forearms"] },
  { name: "Barbell Reverse Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["barbell"], description: "Forearm extensor exercise", muscleGroups: ["forearms"] },
  { name: "Dumbbell Reverse Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell reverse wrist curl", muscleGroups: ["forearms"] },
  { name: "Cable Wrist Curl", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable wrist curl", muscleGroups: ["forearms"] },
  { name: "Wrist Roller", category: "forearms", type: "isolation", difficulty: "intermediate", equipment: ["wrist roller"], description: "Wrist roller exercise", muscleGroups: ["forearms"] },
  { name: "Farmer's Carry", category: "forearms", type: "functional", difficulty: "beginner", equipment: ["dumbbells", "barbell"], description: "Grip strength and forearm endurance", muscleGroups: ["forearms", "grip"] },
  { name: "Plate Pinch", category: "forearms", type: "isolation", difficulty: "intermediate", equipment: ["weight plates"], description: "Grip strength exercise", muscleGroups: ["forearms", "grip"] },
  { name: "Dead Hang", category: "forearms", type: "isolation", difficulty: "beginner", equipment: ["pull-up bar"], description: "Grip endurance", muscleGroups: ["forearms", "grip"] },
  { name: "Zottman Curl", category: "forearms", type: "isolation", difficulty: "intermediate", equipment: ["dumbbells"], description: "Combined curl and reverse curl", muscleGroups: ["biceps", "forearms"] },

  // ===== LEGS =====
  { name: "Barbell Back Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "King of leg exercises", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Barbell Front Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "Quad-focused squat", muscleGroups: ["quads", "core"] },
  { name: "Goblet Squat", category: "legs", type: "compound", difficulty: "beginner", equipment: ["dumbbell"], description: "Beginner-friendly squat", muscleGroups: ["quads", "glutes"] },
  { name: "Dumbbell Squat", category: "legs", type: "compound", difficulty: "beginner", equipment: ["dumbbells"], description: "Dumbbell squat variation", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Machine Leg Press", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Guided leg press", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Hack Squat", category: "legs", type: "compound", difficulty: "beginner", equipment: ["hack squat machine"], description: "Machine squat variation", muscleGroups: ["quads", "glutes"] },
  { name: "Smith Machine Squat", category: "legs", type: "compound", difficulty: "beginner", equipment: ["smith machine"], description: "Guided barbell squat", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Leg Extension", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Quad isolation", muscleGroups: ["quads"] },
  { name: "Leg Curl", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Hamstring isolation", muscleGroups: ["hamstrings"] },
  { name: "Lying Leg Curl", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Lying hamstring curl", muscleGroups: ["hamstrings"] },
  { name: "Seated Leg Curl", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Seated hamstring curl", muscleGroups: ["hamstrings"] },
  { name: "Standing Leg Curl", category: "legs", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Standing hamstring curl", muscleGroups: ["hamstrings"] },
  { name: "Leg Press", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine leg press", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Bulgarian Split Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["bench", "dumbbells"], description: "Single-leg squat variation", muscleGroups: ["quads", "glutes"] },
  { name: "Dumbbell Bulgarian Split Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["bench", "dumbbells"], description: "Dumbbell split squat", muscleGroups: ["quads", "glutes"] },
  { name: "Barbell Bulgarian Split Squat", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["bench", "barbell"], description: "Barbell split squat", muscleGroups: ["quads", "glutes"] },
  { name: "Lunges", category: "legs", type: "compound", difficulty: "beginner", equipment: ["dumbbells"], description: "Walking or stationary lunges", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Barbell Lunges", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Barbell lunges", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Reverse Lunges", category: "legs", type: "compound", difficulty: "beginner", equipment: ["dumbbells"], description: "Reverse lunge variation", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Walking Lunges", category: "legs", type: "compound", difficulty: "beginner", equipment: ["dumbbells"], description: "Walking lunge variation", muscleGroups: ["quads", "glutes", "hamstrings"] },
  { name: "Step-ups", category: "legs", type: "compound", difficulty: "beginner", equipment: ["bench", "dumbbells"], description: "Step-up exercise", muscleGroups: ["quads", "glutes"] },
  { name: "Box Jumps", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["box"], description: "Explosive leg power", muscleGroups: ["quads", "glutes", "calves"] },
  { name: "Jump Squats", category: "legs", type: "compound", difficulty: "intermediate", equipment: ["bodyweight"], description: "Explosive squat variation", muscleGroups: ["quads", "glutes"] },
  { name: "Pistol Squat", category: "legs", type: "compound", difficulty: "advanced", equipment: ["bodyweight"], description: "Single-leg bodyweight squat", muscleGroups: ["quads", "glutes"] },
  { name: "Sissy Squat", category: "legs", type: "isolation", difficulty: "intermediate", equipment: ["bodyweight"], description: "Quad-focused squat", muscleGroups: ["quads"] },
  { name: "Hack Squat Machine", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine hack squat", muscleGroups: ["quads", "glutes"] },
  { name: "Pendulum Squat", category: "legs", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine pendulum squat", muscleGroups: ["quads", "glutes"] },

  // ===== GLUTES =====
  { name: "Hip Thrust", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["bench", "barbell"], description: "Glute-focused hip thrust", muscleGroups: ["glutes"] },
  { name: "Barbell Hip Thrust", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["bench", "barbell"], description: "Barbell hip thrust", muscleGroups: ["glutes"] },
  { name: "Dumbbell Hip Thrust", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["bench", "dumbbell"], description: "Dumbbell hip thrust", muscleGroups: ["glutes"] },
  { name: "Machine Hip Thrust", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine hip thrust", muscleGroups: ["glutes"] },
  { name: "Single Leg Hip Thrust", category: "glutes", type: "compound", difficulty: "intermediate", equipment: ["bench", "barbell"], description: "Single-leg hip thrust", muscleGroups: ["glutes"] },
  { name: "Glute Bridge", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["bodyweight"], description: "Bodyweight glute bridge", muscleGroups: ["glutes"] },
  { name: "Barbell Glute Bridge", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["barbell"], description: "Barbell glute bridge", muscleGroups: ["glutes"] },
  { name: "Cable Pull-through", category: "glutes", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Glute isolation exercise", muscleGroups: ["glutes"] },
  { name: "Machine Glute Kickback", category: "glutes", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine glute kickback", muscleGroups: ["glutes"] },
  { name: "Cable Glute Kickback", category: "glutes", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable glute kickback", muscleGroups: ["glutes"] },
  { name: "Dumbbell Glute Kickback", category: "glutes", type: "isolation", difficulty: "beginner", equipment: ["dumbbell"], description: "Dumbbell glute kickback", muscleGroups: ["glutes"] },
  { name: "Smith Machine Hip Thrust", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["smith machine", "bench"], description: "Smith machine hip thrust", muscleGroups: ["glutes"] },
  { name: "Leg Press (Glute Focus)", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Leg press with glute focus", muscleGroups: ["glutes", "quads"] },
  { name: "V-Squat", category: "glutes", type: "compound", difficulty: "beginner", equipment: ["machine"], description: "Machine V-squat", muscleGroups: ["glutes", "quads"] },

  // ===== CORE =====
  { name: "Barbell Back Squat", category: "core", type: "compound", difficulty: "intermediate", equipment: ["barbell", "squat rack"], description: "Core stability", muscleGroups: ["core", "quads", "glutes"] },
  { name: "Barbell Deadlift", category: "core", type: "compound", difficulty: "intermediate", equipment: ["barbell"], description: "Core stability", muscleGroups: ["core", "back", "glutes"] },
  { name: "Plank", category: "core", type: "isolation", difficulty: "beginner", equipment: ["bodyweight"], description: "Isometric core hold", muscleGroups: ["core"] },
  { name: "Side Plank", category: "core", type: "isolation", difficulty: "beginner", equipment: ["bodyweight"], description: "Side core hold", muscleGroups: ["obliques", "core"] },
  { name: "Ab Wheel Rollout", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["ab wheel"], description: "Advanced core exercise", muscleGroups: ["abs", "core"] },
  { name: "Cable Crunch", category: "core", type: "isolation", difficulty: "beginner", equipment: ["cable machine"], description: "Cable ab crunch", muscleGroups: ["abs"] },
  { name: "Machine Crunch", category: "core", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine ab crunch", muscleGroups: ["abs"] },
  { name: "Decline Sit-ups", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["decline bench"], description: "Decline ab sit-ups", muscleGroups: ["abs"] },
  { name: "Weighted Sit-ups", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["weight plate"], description: "Weighted sit-ups", muscleGroups: ["abs"] },
  { name: "Hanging Leg Raises", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["pull-up bar"], description: "Hanging leg raise", muscleGroups: ["abs", "core"] },
  { name: "Lying Leg Raises", category: "core", type: "isolation", difficulty: "beginner", equipment: ["bench"], description: "Lying leg raise", muscleGroups: ["abs", "core"] },
  { name: "Machine Ab Crunch", category: "core", type: "isolation", difficulty: "beginner", equipment: ["machine"], description: "Machine ab crunch", muscleGroups: ["abs"] },
  { name: "Pallof Press", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["cable machine"], description: "Anti-rotation core exercise", muscleGroups: ["obliques", "core"] },
  { name: "Landmine Rotation", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["landmine"], description: "Rotational core exercise", muscleGroups: ["obliques", "core"] },
  { name: "Russian Twist", category: "core", type: "isolation", difficulty: "beginner", equipment: ["weight plate"], description: "Oblique twist exercise", muscleGroups: ["obliques"] },
  { name: "Suitcase Carry", category: "core", type: "functional", difficulty: "beginner", equipment: ["dumbbell"], description: "Unilateral core stability", muscleGroups: ["obliques", "core"] },
  { name: "Dead Bug", category: "core", type: "isolation", difficulty: "beginner", equipment: ["bodyweight"], description: "Core stability exercise", muscleGroups: ["core"] },
  { name: "Bird Dog", category: "core", type: "isolation", difficulty: "beginner", equipment: ["bodyweight"], description: "Core stability exercise", muscleGroups: ["core"] },
  { name: "Ab Coaster", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["ab coaster"], description: "Ab coaster machine", muscleGroups: ["abs"] },
  { name: "Decline Crunch", category: "core", type: "isolation", difficulty: "intermediate", equipment: ["decline bench"], description: "Decline ab crunch", muscleGroups: ["abs"] },

  // ===== CARDIO =====
  { name: "Treadmill Running", category: "cardio", type: "cardio", difficulty: "beginner", equipment: ["treadmill"], description: "Steady-state cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Incline Treadmill Walking", category: "cardio", type: "cardio", difficulty: "beginner", equipment: ["treadmill"], description: "Low-impact cardio", muscleGroups: ["legs", "glutes"] },
  { name: "Stationary Bike", category: "cardio", type: "cardio", difficulty: "beginner", equipment: ["stationary bike"], description: "Low-impact leg cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Rowing Machine", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["rowing machine"], description: "Full-body cardio", muscleGroups: ["back", "legs", "cardio"] },
  { name: "Elliptical Machine", category: "cardio", type: "cardio", difficulty: "beginner", equipment: ["elliptical"], description: "Low-impact full-body cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Stair Climber", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["stair climber"], description: "Intense leg cardio", muscleGroups: ["legs", "glutes", "cardio"] },
  { name: "Jump Rope", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["jump rope"], description: "Explosive cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Burpees", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["bodyweight"], description: "Full-body explosive cardio", muscleGroups: ["cardio", "core", "chest"] },
  { name: "Mountain Climbers", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["bodyweight"], description: "Core and cardio", muscleGroups: ["core", "cardio"] },
  { name: "Battle Ropes", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["battle ropes"], description: "Explosive cardio", muscleGroups: ["shoulders", "cardio"] },
  { name: "Sled Push", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["sled"], description: "Explosive leg cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Sled Pull", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["sled"], description: "Explosive leg cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Assault Bike", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["assault bike"], description: "High-intensity cardio", muscleGroups: ["legs", "cardio"] },
  { name: "Swimming", category: "cardio", type: "cardio", difficulty: "intermediate", equipment: ["pool"], description: "Full-body low-impact cardio", muscleGroups: ["cardio", "back", "shoulders"] },
  { name: "Sprints", category: "cardio", type: "cardio", difficulty: "advanced", equipment: ["bodyweight"], description: "High-intensity running", muscleGroups: ["legs", "cardio"] },
  { name: "Agility Ladder", category: "cardio", type: "functional", difficulty: "intermediate", equipment: ["agility ladder"], description: "Footwork and agility", muscleGroups: ["legs", "cardio"] },
  { name: "Box Sprints", category: "cardio", type: "cardio", difficulty: "advanced", equipment: ["box"], description: "Explosive sprint training", muscleGroups: ["legs", "cardio"] },

  // ===== FUNCTIONAL =====
  { name: "Farmer's Carry", category: "functional", type: "functional", difficulty: "beginner", equipment: ["dumbbells"], description: "Grip and core strength", muscleGroups: ["forearms", "core"] },
  { name: "Sandbag Carry", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["sandbag"], description: "Unbalanced load carry", muscleGroups: ["core", "grip"] },
  { name: "Kettlebell Swing", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["kettlebell"], description: "Explosive hip drive", muscleGroups: ["glutes", "hamstrings", "cardio"] },
  { name: "Kettlebell Turkish Get-up", category: "functional", type: "functional", difficulty: "advanced", equipment: ["kettlebell"], description: "Full-body mobility and strength", muscleGroups: ["shoulders", "core", "glutes"] },
  { name: "Medicine Ball Slam", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["medicine ball"], description: "Explosive power", muscleGroups: ["shoulders", "core", "cardio"] },
  { name: "Medicine Ball Chest Pass", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["medicine ball"], description: "Explosive chest power", muscleGroups: ["chest", "shoulders", "cardio"] },
  { name: "Tire Flip", category: "functional", type: "functional", difficulty: "advanced", equipment: ["tire"], description: "Full-body explosive power", muscleGroups: ["back", "legs", "cardio"] },
  { name: "Prowler Push", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["prowler"], description: "Explosive leg power", muscleGroups: ["legs", "cardio"] },
  { name: "Prowler Drag", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["prowler"], description: "Explosive leg power", muscleGroups: ["legs", "cardio"] },
  { name: "Sled Drag", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["sled"], description: "Leg endurance", muscleGroups: ["legs", "cardio"] },
  { name: "Rope Climb", category: "functional", type: "functional", difficulty: "advanced", equipment: ["rope"], description: "Full-body pulling power", muscleGroups: ["back", "arms", "core"] },
  { name: "Wall Ball", category: "functional", type: "functional", difficulty: "intermediate", equipment: ["medicine ball"], description: "Explosive power", muscleGroups: ["legs", "shoulders", "cardio"] },
];

export const MUSCLE_GROUPS = [
  "chest",
  "back",
  "shoulders",
  "biceps",
  "triceps",
  "forearms",
  "quads",
  "hamstrings",
  "glutes",
  "calves",
  "core",
  "abs",
  "obliques",
  "lats",
  "traps",
  "rear delts",
  "front delts",
  "lateral delts",
  "upper chest",
  "lower chest",
  "upper back",
  "grip",
];

export const EXERCISE_CATEGORIES = ["chest", "back", "shoulders", "biceps", "triceps", "forearms", "legs", "glutes", "core", "cardio", "functional"];
